name: aptos

on:
  pull_request:

jobs:
  test:
    name: Aptos Test
    runs-on: ubuntu-latest
    # https://github.com/aptos-labs/aptos-core/releases/tag/aptos-cli-v4.2.3
    # https://github.com/aptos-labs/aptos-core/commit/8689b9aaedb8c61704167028ba89bb05074c3b50
    container: aptoslabs/tools:nightly_8689b9aaedb8c61704167028ba89bb05074c3b50
    defaults:
      run:
        working-directory: aptos
    steps:
      - uses: actions/checkout@v4
      - run: sh ci.sh
